export const INCH_PIXEL_VALUE = 96;
export const CENTIMETER_PIXEL_VALUE = INCH_PIXEL_VALUE / 2.54;
export const MILLIMETER_PIXEL_VALUE = CENTIMETER_PIXEL_VALUE / 10;
export const QUARTER_PIXEL_VALUE = CENTIMETER_PIXEL_VALUE / 40;
export const PICA_PIXEL_VALUE = INCH_PIXEL_VALUE / 6;
export const POINT_PIXEL_VALUE = PICA_PIXEL_VALUE / 12;
